# Generated by Django 4.0.3 on 2022-03-17 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_c_d_e_f_g_h_i_j_k_l_m_n_o_p_q_r_s_t_u_v_w_x_y_z'),
    ]

    operations = [
        migrations.DeleteModel(
            name='D',
        ),
        migrations.DeleteModel(
            name='E',
        ),
        migrations.DeleteModel(
            name='F',
        ),
        migrations.DeleteModel(
            name='G',
        ),
        migrations.DeleteModel(
            name='H',
        ),
        migrations.DeleteModel(
            name='I',
        ),
        migrations.DeleteModel(
            name='J',
        ),
        migrations.DeleteModel(
            name='K',
        ),
        migrations.DeleteModel(
            name='L',
        ),
        migrations.DeleteModel(
            name='M',
        ),
        migrations.DeleteModel(
            name='N',
        ),
        migrations.DeleteModel(
            name='O',
        ),
        migrations.DeleteModel(
            name='P',
        ),
        migrations.DeleteModel(
            name='Q',
        ),
        migrations.DeleteModel(
            name='R',
        ),
        migrations.DeleteModel(
            name='S',
        ),
        migrations.DeleteModel(
            name='T',
        ),
        migrations.DeleteModel(
            name='U',
        ),
        migrations.DeleteModel(
            name='V',
        ),
        migrations.DeleteModel(
            name='W',
        ),
        migrations.DeleteModel(
            name='X',
        ),
        migrations.DeleteModel(
            name='Y',
        ),
        migrations.DeleteModel(
            name='Z',
        ),
    ]
