# Generated by Django 4.0.3 on 2022-03-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_d_delete_e_delete_f_delete_g_delete_h_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='C',
            new_name='CC',
        ),
    ]
